# Generated by Django 4.2.6 on 2023-12-13 02:30

from django.db import migrations

def load_initial_data(apps, schema_editor):
    row_model = apps.get_model('theatrehome', 'Row')
    seat_model = apps.get_model('theatrehome', 'Seat')
    rows = 13
    seats_row1_2 = 21
    seats_row3_4 = 17
    seats_row5 = 15
    for i in range(1, rows + 1):
        if i in {1, 2}:
            row = row_model.objects.create(price=150)
            seat_numbers = range(1, seats_row1_2 + 1)
        elif i in {3, 4}:
            row = row_model.objects.create(price=200)
            seat_numbers = range(1, seats_row3_4 + 1)
        elif 5 <= i <= 9:
            row = row_model.objects.create(price=250)
            seat_numbers = range(1, seats_row5 + 1)
        else:
            row = row_model.objects.create(price=300)
            seat_numbers = range(1, seats_row5 + 1)

        for j in seat_numbers:
            seat_model.objects.create(seat_no=j, row=row)


class Migration(migrations.Migration):

    dependencies = [
        ('theatrehome', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_initial_data)
    ]
